/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['[_nghost-%COMP%] {\r\n    .date {\r\n        text-align: center;\r\n        color: black;\r\n    }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V0aGFuL3Byb2dyYW1taW5nL2RlYnVnZ2luZy9Nb2JpbGVUaW1lUGlja2VyL2Rldi9zcmMvdGltZS1waWNrZXIuY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXRoYW4vcHJvZ3JhbW1pbmcvZGVidWdnaW5nL01vYmlsZVRpbWVQaWNrZXIvZGV2L3NyYy90aW1lLXBpY2tlci5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
