/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['[_nghost-%COMP%] {\r\n    .date {\r\n        text-align: center;\r\n        color: black;\r\n    }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbWVsYW1lZS9Eb2N1bWVudHMvcmVwb3MvTW9iaWxlVGltZVBpY2tlci9kZXYvc3JjL3RpbWUtcGlja2VyLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL21lbGFtZWUvRG9jdW1lbnRzL3JlcG9zL01vYmlsZVRpbWVQaWNrZXIvZGV2L3NyYy90aW1lLXBpY2tlci5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
